scalar Date

# 订单服务模块
type Order {
  # 订单 ID
  id: Int
  # 创建时间
  created: Date
  # 订单价格
  price: Float
}

extend type User {
  orders(userId: Int): [Order] @rest(
    endpoint: "endpoint2001"
    path: "/users/:userId/orders"
    parentAccessorMap: "{ id: userId }"
  )
}

extend type Product {
  orders(productId: Int): [Order] @rest(
    endpoint: "endpoint2001"
    path: "/products/:productId/orders"
    parentAccessorMap: "{ id: productId }"
  )
}

input OrderInput {
  created: Date!
  price: Float!
  userId: Int
  productId: Int
}

type Query {
  order(orderId: Int!): Order @rest(
    endpoint: "endpoint2001"
    path: "/orders/:orderId"
  )
  orders: [Order] @rest(
    endpoint: "endpoint2001"
    path: "/orders"
  )
}

type Mutation {
  createOrder(body: OrderInput): Order @rest(
    endpoint: "endpoint2001"
    path: "/orders"
    method: "post"
  )
  updateOrder( orderId: Int! body: OrderInput ): Order @rest(
    endpoint: "endpoint2001"
    path: "/orders/:orderId"
    method: "patch"
  )
}

