directive @rest(
  endpoint: String
  path: String
  method: String
  rootAccessorMap: String
  responseAccessor: String
) on FIELD_DEFINITION

enum ProductSize {
  M
  L
  XL
  XXL
}

type Product {
  id: Int
  title: String
  description: String
  price: Float
  size: ProductSize
}

extend type User {
  collections(userId: Int): [Product] @rest(
    endpoint: "endpoint2001"
    path: "/users/:userId/products"
    rootAccessorMap: "{ id, userId }"
  )
}

extend type Order {
  product(orderId: Int): Product @rest(
    endpoint: "endpoint2001"
    path: "/orders/:orderId/products"
    rootAccessorMap: "{ id, orderId }"
    responseAccessor: "[0]"
  )
}

input ProductInput {
  title: String!
  description: String
  price: Float!
  size: ProductSize!
  userId: Int
  orderId: Int
}

extend type Query {
  product(productId: Int!): Product @rest(
    endpoint: "endpoint2001"
    path: "/products/:productId"
  )
  products: [Product] @rest(
    endpoint: "endpoint2001"
    path: "/products"
  )
}

extend type Mutation {
  createProduct(body: ProductInput): Product @rest(
    endpoint: "endpoint2001"
    path: "/products"
    method: "post"
  )
  updateProduct( productId: Int! body: ProductInput ): Product @rest(
    endpoint: "endpoint2001"
    path: "/products/:productId"
    method: "patch"
  )
}
